spring.application.name=ServerApplication
server.port=6789

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dist_sys
spring.datasource.username=nodes_health
spring.datasource.password=yourPass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true